### ISSUE TITLE
Error at Step 6

### ISSUE THREAD

**Issue by psychedelictrip** [juanonsoftware/Dockers#1]
This is my dockerfile
`# Build an intermediate image then use it to reduce layers for our real image
FROM mcr.microsoft.com/windows/servercore:10.0.14393.1066`
`# Build variable to allow passing in a specific version of ElasticSearch
ARG ELASTICSEARCH_VERSION=7.6.2
ARG ELASTICSEARCH_SOURCE=elasticsearch-${ELASTICSEARCH_VERSION}
ARG ELASTICSEARCH_ZIP=elasticsearch-${ELASTICSEARCH_VERSION}-windows-x86_64.zip`
`# Copy apps from sources to root directory
COPY sources `
`# Extracts the zip to a folder then delete the zip
RUN Expand-Archive -Path $Env:ELASTICSEARCH_ZIP -DestinationPath C:\; \
	Remove-Item -Path $Env:ELASTICSEARCH_ZIP`
`# ELASTICSEARCH_HOME is used by RunElasticSearch.cmd file to launch ElasticSearch.
ENV ELASTICSEARCH_HOME C:\\elasticsearch-${ELASTICSEARCH_SOURCE}`
`# Copy config files
COPY config\\elasticsearch.yml ${ELASTICSEARCH_HOME}/config/`
`# Call file to start ELASTICSEARCH
CMD ["C:/RunElasticSearch.cmd"]`
`EXPOSE 9200 9300`

This is the error I got
``Step 6/10 : RUN Expand-Archive -Path $Env:ELASTICSEARCH_ZIP -DestinationPath C:\;       Remove-Item -Path $Env:ELASTICSEARCH_ZIP
 ---> Running in 2a6dga7a30fb
'Expand-Archive' is not recognized as an internal or external command,
operable program or batch file.
The command 'cmd /S /C Expand-Archive -Path $Env:ELASTICSEARCH_ZIP -DestinationPath C:\;        Remove-Item -Path $Env:ELASTICSEARCH_ZIP' returned a non-zero code: 1``

Do you know how to fix this issue? Thank you!

**Comment by juanonsoftware** [comment]
It looks like the cmdlet Expand-Archive does not exist.

Can you check your powershell version? for me the PS version is 5.1.

Ref: https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.archive/expand-archive?view=powershell-5.1

**Comment by psychedelictrip** [comment]
Hi Juan, 

My PS version is  5.1.14393.3471. I dont think it's because of my PS. Perhaps, it's my dockerfile or  maybe my docker version? 

Currently I am using docker version  19.03.5.

**Comment by juanonsoftware** [comment]
I see you have this: ARG ELASTICSEARCH_VERSION=7.6.2
So you will use the release 7.6.2. Besure that you download the zip file at put it into folder ElasticSearch\sources. For me I only have this: elasticsearch-7.6.0-windows-x86_64.zip

**Comment by psychedelictrip** [comment]
Yeap, I downloaded the correct zip file, elasticsearch-7.6.2-windows-x86_64.zip. I still got the same error.
May I know what needs to be inside the sources folder? 
Currently, I only have the elasticsearch-7.6.2-windows-x86_64.zip and RunElasticSearch.cmd files only.

**Comment by psychedelictrip** [comment]
Also inside Elasticsearch folder, currently I have the Dockerfile and elasticsearch.yml and the "sources" folder.

**Comment by psychedelictrip** [comment]
Hi, do you know anywhere I can seek for help?

**Comment by juanonsoftware** [comment]
Great as you resolved the issue!

**Comment by psychedelictrip** [comment]
hey man, i cant access the elaticsearch status when i input localhost:9200 in my web browser. I am new to docker. I am using windows server 2016. Must I do something first to connect the docker host to the docker?
